@startuml
title Жизненный цикл банковской карты

[*] --> Активная : [Выпуск карты]

state Активная {
    state Обычная
    state Премиум
    [*] --> Обычная
    Обычная --> Премиум : [Изменен статус]
    Премиум --> Обычная : [Изменен статус]
}

Активная --> Заблокированная : [Попытка мошенничества]
Активная --> Заблокированная : [Блокировка по запросу клиента]
Активная --> Заблокированная : [3 ошибки PIN]
Активная --> Утерянная : [Заявление об утере]
Активная --> Просроченная : [Истечение срока действия]

Заблокированная --> Активная : [Разблокировка]
Заблокированная --> [*] : [Закрытие карты]

Просроченная --> [*] : [Закрытие карты]

Утерянная --> Активная : [Карта найдена]
Утерянная --> [*] : [Закрытие карты]

@enduml