@startuml
left to right direction
actor "Ресторанный критик" as fc
rectangle Ресторан {
  usecase "Есть" as UC1
  usecase "Платить" as UC2
  usecase "Пить" as UC3
  usecase "Составлять отзыв" as UC4
}
fc --> UC1
fc --> UC2
fc --> UC3
fc --> UC4
@enduml
