@startuml

|Клиент|
start
:Регистрация на сайте или вход в аккаунт;
|Система|
:Подтверждение учётных данных;
|Клиент|
:Выбор товаров и добавление в корзину;
:Переход к оформлению заказа;

if (Применяется промокод или\nавтоматическая скидка?) then (да)
  |Система|
  :Проверка промокода или\nсоответствия условиям скидки;
  if (Условия применения\nскидки выполнены?) then (да)
    :Обновление суммы заказа;
  else (нет)
    switch ( Вывод ошибки )
        case ()
        :Неверный промокод;
        case () 
        :Превышение лимита\nна использование;
        case ()
        :Промокод не действует\nна выбранные товары;
    endswitch
  endif
else (нет)
endif


|Система|
:Проверка наличия товаров на складе;

if (Все товары в наличии?) then (да)
else (нет)
  :Уведомление клиента об отсутствии товара;
  |Клиент|
  if (Выбрать альтернативный\nили удалить часть товаров?) then (да)
    :Возврат для замены товара\nили удаления из заказа;
    stop
  else (Нет)
    |Система|
    if (Оставить заказ в ожидании?) then (да)
    :Перевод заказа в статус "Ожидание поставки";
    :Уведомление клиента о поступлении товара;
    stop
    else (нет)
    stop
    endif
  endif
endif


fork
  |Клиент|
  :Выбор способа доставки и оплаты;
  |Система|
  :Проверка платежных данных и\nпроведение транзакции;
fork again
|Система|
  :Уведомление склада о\nнеобходимости сборки заказа;
  |Склад|
  :Комплектация заказа;
end fork
|Система|
  if (Оплата прошла успешно?) then (да)
    :Подтверждение успешной оплаты;
  else (нет)
    repeat
    :Уведомление о сбое оплаты\n(недостаточно средств; неверные платежные данные; платёжная система недоступна);
      |Клиент|
      :Выбор действия после сбоя;
      if ('Повторить попытку или изменить способ оплаты'?) then (да)
        |Система|
        :Проверка платежных данных и\nпроведение транзакции;
      else (нет)
        |Система|
        :Отмена заказа;
        if (Средства были списаны?) then (Да)
        :Возврат средств клиенту;
        else (нет)
        endif
        stop
      endif
    repeat while (Оплата прошла?) is (нет)
  endif



|Система|
:Обновление статуса заказа;

|Клиент|
:Получение уведомлений о статусе заказа;

stop
@enduml